### ISSUE TITLE
Add CLI Support

### ISSUE THREAD

**Issue by arcticShadow** [LingyuCoder/check-changelog#1]
With CLI support, this can easily be added to NPM lifecycle scripts, for example prepublish.

**Comment by arcticShadow** [comment]
Any feedback on this PR?

**Comment by LingyuCoder** [comment]
Sorry, I missed this in my mailbox, I have merged it and published a new
version 0.0.2, thank u so much

2016-03-24 5:34 GMT+08:00 Cole Diffin notifications@github.com:
